package:
  version: 1.1.11
  url: https://github.com/pooza/ginseng-redis
  authors:
    - Tatsuya Koishi
  email:
    - tkoishi@b-shock.co.jp
  description: ginseng Redis libraries
  license: MIT
redis:
  dsn: null
  retry:
    limit: 3
    seconds: 1
