package:
  authors:
    - Tatsuya Koishi
  description: ginseng Redis libraries
  email:
    - tkoishi@b-shock.co.jp
  license: MIT
  url: https://github.com/pooza/ginseng-redis
  version: 2.0.1
redis:
  dsn: null
  retry:
    limit: 3
    seconds: 1
